const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
for(const file of ['index.html','index-fr.html'])test(`${file}: compact conversion flow and honest integration states`,()=>{
 const html=fs.readFileSync(path.join(__dirname,'..',file),'utf8');
 const signals=html.match(/<section id="detected-changes"[\s\S]*?<\/section>/)[0];
 assert.equal((signals.match(/<li>/g)||[]).length,6);
 assert.equal((signals.match(/<h3(?:\s[^>]*)?>/g)||[]).length,6);
 assert.doesNotMatch(signals,/home-signals-track|home-signals-pause/);
 const positions=['home-focused-hero','id="radar-preview"','id="detected-changes"','id="customer-proof"','id="pricing"','id="faq"','<footer','id="newsletter"'].map(token=>html.indexOf(token));
 assert.ok(positions.every((n,i)=>n>=0&&(!i||n>positions[i-1])));
 assert.doesNotMatch(html,/id="comparison"|id="solution-preview"|id="prospect-example"|home-final-cta/);
 assert.doesNotMatch(html,/class="home-steps"|class="prospect-card"|class="content-page home-output"/);
 assert.equal((html.match(/class="home-testimonial"/g)||[]).length,3);
 const testimonials=html.match(/<section id="customer-proof"[\s\S]*?<\/section>/)[0];
 assert.doesNotMatch(testimonials,/home-testimonial-disclosure/);
 assert.doesNotMatch(testimonials,/home-testimonial-label|EXEMPLE ILLUSTRATIF|ILLUSTRATIVE EXAMPLE/);
 assert.doesNotMatch(testimonials,/data-customer-stories|data-customer-preview/);
 const hero=html.match(/<section class="hero[\s\S]*?<\/section>/)[0];
 assert.equal((hero.match(/data-book-demo/g)||[]).length,1);
 assert.equal((hero.match(/class="page-button page-button--secondary"/g)||[]).length,1);
 assert.doesNotMatch(hero,/href="\/pricing/);
 assert.match(hero,file==='index-fr.html' ? /Nous emménageons à San Francisco/ : /We’re moving to San Francisco/);
 assert.equal((html.match(/<details class="pricing-faq-item">/g)||[]).length,3);
 assert.doesNotMatch(html,/<details[^>]*\bopen\b/);
 assert.match(html,/data-pricing-range[^>]*value="2"/);
 const newsletter=html.match(/<section id="newsletter"[\s\S]*?<\/section>/)[0];
 assert.doesNotMatch(newsletter,/<fieldset[^>]*disabled/);
 assert.match(newsletter,/data-newsletter-form/);
 assert.match(newsletter,/aria-label="(?:Votre email|Your email)"/);
 assert.doesNotMatch(newsletter,/<label|Pas de spam|No spam|temporairement|temporarily/);
 assert.match(newsletter,/type="email"/);
 assert.match(newsletter,/action="\/api\/newsletter"/);
});
