const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
for(const file of ['index.html','index-fr.html'])test(`${file}: compact conversion flow and honest integration states`,()=>{
 const html=fs.readFileSync(path.join(__dirname,'..',file),'utf8');
 const section=html.match(/<section id="comparison"[\s\S]*?<\/section>/)[0];
 assert.equal((section.match(/<li(?:\s[^>]*)?>/g)||[]).length,8);
 assert.doesNotMatch(section,/comparison-example|<dl>|<h3>|comparison-disclaimer/);
 const positions=['home-focused-hero','id="comparison"','id="solution-preview"','id="prospect-example"','id="customer-proof"','id="pricing"','id="faq"','<footer','id="newsletter"'].map(token=>html.indexOf(token));
 assert.ok(positions.every((n,i)=>n>=0&&(!i||n>positions[i-1])));
 assert.doesNotMatch(html,/id="signals"|home-final-cta/);
 assert.equal((html.match(/class="home-product-drawer"/g)||[]).length,1);
 assert.doesNotMatch(html,/class="home-steps"|class="prospect-card"|class="content-page home-output"/);
 assert.equal((html.match(/class="home-testimonial"/g)||[]).length,3);
 const testimonials=html.match(/<section id="customer-proof"[\s\S]*?<\/section>/)[0];
 assert.doesNotMatch(testimonials,/home-testimonial-disclosure/);
 assert.doesNotMatch(testimonials,/home-testimonial-label|EXEMPLE ILLUSTRATIF|ILLUSTRATIVE EXAMPLE/);
 assert.doesNotMatch(testimonials,/data-customer-stories|data-customer-preview/);
 const hero=html.match(/<section class="hero[\s\S]*?<\/section>/)[0];
 assert.equal((hero.match(/data-book-demo/g)||[]).length,1);
 assert.equal((hero.match(/class="page-button page-button--secondary"/g)||[]).length,1);
 assert.doesNotMatch(hero,/href="\/pricing/);
 assert.match(hero,file==='index-fr.html' ? /Synthetic Swarm déménage à San Francisco\./ : /Synthetic Swarm moves to San Francisco\./);
 assert.equal((hero.match(/class="hero-eyebrow-separator"/g)||[]).length,2);
 assert.equal((html.match(/<details class="pricing-faq-item">/g)||[]).length,3);
 assert.doesNotMatch(html,/<details[^>]*\bopen\b/);
 assert.match(html,/data-pricing-range[^>]*value="2"/);
 const newsletter=html.match(/<section id="newsletter"[\s\S]*?<\/section>/)[0];
 assert.match(newsletter,/<fieldset disabled>/);
 assert.match(newsletter,/aria-label="(?:Votre email|Your email)"/);
 assert.doesNotMatch(newsletter,/<label|newsletter-status|Pas de spam|No spam|temporairement|temporarily/);
 assert.match(newsletter,/type="email"/);
 assert.doesNotMatch(newsletter,/<form[^>]*action=/);
 const output=html.match(/<section id="solution-preview"[\s\S]*?<\/section>/)[0];
 assert.doesNotMatch(output,/solution-disclaimer|Fictional example|Exemple fictif/);
 assert.match(output,/class="home-product-window"/);
 assert.doesNotMatch(output,/class="solution-(?:system|engine|target|transform|output)"/);
 assert.doesNotMatch(output,/class="solution-flow"|class="solution-node/);
 assert.doesNotMatch(output,/<dl>|<time/);
 assert.doesNotMatch(output,/href="(?:tel:|mailto:|https:\/\/.*linkedin)/);
});
